export const SELECTORS = {
    DESTINATION : 'input[type="search"]',
    DESTINATION_DROPDOWN_ITEM : '.q-virtual-scroll__content [role="listitem"]',
    TRANSPORT_TYPE : 'i.fa-plane',
    DROPDOWN_OPTION : '[role="option"] .q-item__section',
    DEPARTURE_FROM : '.ct-submenu i.fa-suitcase-rolling',
    NR_OF_NIGHTS : 'i.fa-clouds-moon',
    DATE_OF_DEPARTURE: 'i.fa-calendar-alt',
    NR_OF_ROOMS : 'i.fa-bed',
    NR_OF_ADULTS : 'i.fa-user',
    NR_OF_KIDS : 'i.fa-child',
    KID_AGE : '[helper="La întoarcere"]',
    SEARCH_BTN : 'a.ct-search-btn',
    RESULT_TITLE: 'h2.ct-item-title',
    PRICE: 'div.ct-item-sell-price',
}