name: Run Script

on: push

jobs:
  holiday-scraper:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        with:
          command: npx cypress run
          browser: chrome
          